name: OpenNicks
version: '1.1'
main: de.prime4g.openNicks.OpenNicks
api-version: '1.21'
authors: [ LE_code ]
depend: [ 'PlaceholderAPI' ]

commands:
  nickname:
    description: OpenNicks command
    usage: /nickname <nick>
    aliases: [nick]
    permissions: opennicks.nickname